use_frameworks!

platform :ios, '10.0'

target 'LibraryTest_Example' do
  pod 'LibraryTest', :path => '../'

  target 'LibraryTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
